### ISSUE TITLE
Fails to load, error message

### ISSUE THREAD

**Issue by aurel-g** [blueraincoatli/comfyUI_SillyNodes#4]
On linux with Python 3.11 I got this error messages at ComfyUI's startup:

```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/comfyUI_SillyNodes/__init__.py", line 1, in <module>
    import pyautogui
  File "/mnt/comfyui/env/python3.11/ba4510c6bcae1b1f8e48572681640499/lib/python3.11/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/mnt/comfyui/env/python3.11/ba4510c6bcae1b1f8e48572681640499/lib/python3.11/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
                       ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'DISPLAY'

Cannot import /mnt/comfyui/app/custom_nodes/comfyUI_SillyNodes module for custom nodes: 'DISPLAY'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.1 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/comfyUI_SillyNodes

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by blueraincoatli** [comment]
please use this command to check if your system has  a correct display environment :
echo $DISPLAY
or,
env | grep DISPLAY

**Comment by aurel-g** [comment]
Hi,

it's empty. I use an LXC container without graphical interface to host my ComfyUI environment.
I will test in an other environment.

**Comment by blueraincoatli** [comment]
I tested on my Ubuntu, it shows :0, that means I have a display environment. it can be load, but there is another problem when I run the node. It seems like some requirements should be downgrade. 
BTW, I am not a coder, I made this node by GPT, so I couldn't give you too much advise, sorry 😭
